function varargout=info
% DEMO application information file

% ***	
% ***	 Copyright 2002, Vanderbilt University. All rights reserved.
% ***
% ***    This program is distributed in the hope that it will be useful,
% ***    but WITHOUT ANY WARRANTY; without even the implied warranty of
% ***    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% ***
% ***

% Written by Gyula Simon, gyula.simon@vanderbilt.edu
% Last modified: Sep 18, 2002  by GYS

title1='Application DEMO';
str1={  'This application demonstrates the basic capabilities of Prowler.'; ...
        '';...
        'You can use your mouse to interact with the simulation:';...
        ' - Click on the white area of the figure to move the transmitter mote' ;...
        ' - Click on a mote''s dot to see memory dump';...
        '';...
        'What''s happening in the demo?';...
        '';...
        ' - A transmitter mote is transmitting a message in every second';...
        ' - The receiving motes retransmit the message (flood)' ;...
        ' - The received/sent message IDs are shown on the motes';...
        '';...
        'What do the colors mean?';...
        '';...
        ' - Small red dots indicate motes with pending transmission';...
        ' - Big red dots indicate transmitting motes';... 
        ' - Small green dots indicate receiving motes';...
        ' - Green LED is toggled when a message is received succesfully';...
        ' - Yellow LED is toggled when a collided message is received';...
        '';...
        'Try also demo_opt from the command window.';...
        '';...
        ''};
if nargout==0
    helpwin({ title1, str1}, 'Application Info')
else
    varargout={ title1, str1};
end
